### ISSUE TITLE
500 Internal server error for options

### ISSUE THREAD

**Issue by cweiske** [ImageMagick/Website6#2]
The options linked at https://legacy.imagemagick.org/Usage/text/ bring a "500 Internal Server Error" page.

Example:
- https://legacy.imagemagick.org/Usage/option_link.cgi?strokewidth
- https://legacy.imagemagick.org/Usage/option_link.cgi?interword-spacing

**Comment by dlemstra** [comment]
Thanks for reporting this, the issue has been resolved.
