### ISSUE TITLE
Can not access API documentation for Magick++ v6 through the legacy website

### ISSUE THREAD

**Issue by pipatron** [ImageMagick/Website6#4]
I'm trying to find documentation for the v6 Magick++ API but none of the links on the [website](https://legacy.imagemagick.org/script/index.php) works:

[Develop](https://legacy.imagemagick.org/script/develop.php) takes me to [Magick++](https://legacy.imagemagick.org/script/magick++.php) which has a [Documentation](https://legacy.imagemagick.org/script/magick++.php#documentation) stating:

>Detailed [documentation](https://legacy.imagemagick.org/api/magick++-classes.php) is provided for all Magick++ classes, class methods, and template functions which comprise the API. 

The website at `https://legacy.imagemagick.org/api/magick++-classes.php` is however empty except for the standard imagemagick.org header (at least in Firefox ESR and 94). At the moment I have no other browser to try it on.

There is also a link at the top of the page:

> [Magick++ API](https://imagemagick.org/api/Magick++/index.html) is the object-oriented C++ API to the ImageMagick image-processing library.

But this takes me to the v7 API `https://imagemagick.org/api/Magick++/index.html`. From this link I did manage to find the v6 API by just prepending _"legacy."_ to the domain name, so maybe that's a very simple fix.

**Comment by dlemstra** [comment]
Thanks for reporting this. A fix for this was pushed and it will probably take a couple of days before our website will be updated.
